# Copyright (c) 2017 SUSE LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Pod
metadata:
  name: velum-private
  labels:
    name: velum-private
spec:
  hostNetwork: false
  containers:
  - name: velum-mariadb
    image: sles12/mariadb:10.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "salt"
    - name: MYSQL_DISABLE_REMOTE_ROOT
      value: "false"
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: mariadb-data
      - mountPath: /var/run/mysql
        name: mariadb-unix-socket
      - mountPath: /etc/my.cnf.d/skip-networking.cnf
        name: mariadb-config-skip-networking
        readOnly: True
  volumes:
    - name: mariadb-data
      hostPath:
        path: /var/lib/mysql
    - name: mariadb-unix-socket
      hostPath:
        path: /var/run/mysql
    - name: mariadb-config-skip-networking
      hostPath:
        path: /usr/share/caasp-container-manifests/config/mysql/skip-networking.cnf
