apiVersion: v1
kind: Pod
metadata:
  name: salt
  labels:
    name: salt
spec:
  hostNetwork: true
  containers:
  - name: salt-master
    image: sles12/salt-master:2015.8.12
    volumeMounts:
    - mountPath: /etc/salt/master.d
      name: salt-master-config
    - mountPath: /srv/salt
      name: salt-master
    - mountPath: /srv/pillar
      name: salt-pillar
    - mountPath: /srv/pillar/vars.sls
      name: salt-pillar-vars
    - mountPath: /var/run/salt/master
      name: salt-sock-dir
  - name: salt-api
    image: sles12/salt-api:2015.8.12
    volumeMounts:
    - mountPath: /etc/salt/master.d
      name: salt-master-config
    - mountPath: /var/run/salt/master
      name: salt-sock-dir
  - name: salt-minion-ca
    image: sles12/salt-minion:2015.8.12
    volumeMounts:
    - mountPath: /etc/salt/minion.d/minion.conf
      name: salt-minion-ca-config
    - mountPath: /etc/salt/minion.d/signing_policies.conf
      name: salt-minion-ca-signing-policies
    - mountPath: /etc/salt/grains
      name: salt-minion-ca-grains
  volumes:
    - name: salt-master-config
      hostPath:
        path: $TODO_PREFIX/config/salt/master.d # FIXME: prefix for this package (config folder)
    - name: salt-master
      hostPath:
        path: $TODO_SALT_STATES # FIXME: where are salt states installed in microos?
    - name: salt-pillar
      hostPath:
        path: $TODO_SALT_PILLAR # FIXME: where is salt pillar installed in microos?
    - name: salt-sock-dir
      hostPath:
        path: $TODO_SALT_MASTER_SOCK_DIR # FIXME: where is the salt master sock dir located in microos?
    - name: salt-minion-ca-grains
      hostPath:
        path: $TODO_PREFIX/config/salt/grains/ca # FIXME: prefix for this package (config folder)
    - name: salt-minion-ca-config
      hostPath:
        path: $TODO_PREFIX/config/salt/minion.d-ca/minion.conf # FIXME: prefix for this package (config folder)
    - name: salt-minion-ca-signing-policies
      hostPath:
        path: $TODO_PREFIX/config/salt/minion.d-ca/signing_policies.conf # FIXME: prefix for this package (config folder)
